### ISSUE TITLE
npm isn't picking up the readme

### ISSUE THREAD

**Issue by tmcw** [asadm/codemirror-copilot#9]
Oddly, https://www.npmjs.com/package/codemirror-copilot is blank. Should be fixable, probably by including `README.md` in files.

**Comment by asadm** [comment]
It's picking up README from here: https://github.com/asadm/codemirror-copilot/tree/main/packages/codemirror-copilot

We can just remove that and symlink root one there (or vice versa) 🤔

**Comment by tmcw** [comment]
Should be fixed in #10, will test out with the next release.
